displayName=Five Active
author=BSW Magic
description=Only five skills, five bosses and five quests are active at a time. Roll new ones as you complete them.
tags=ironman,snowflake,restricted,gamemode,challenge,roll,random
plugins=com.bswmagicgaming.fiveactive.FiveActivePlugin
build=standard
