package com.bswmagicgaming.fiveactive;

import com.google.common.collect.ImmutableSet;
import java.util.Arrays;
import java.util.Collections;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import net.runelite.api.Quest;
import static net.runelite.api.Quest.*;

/**
 * Direct quest / miniquest prerequisites for every quest. Only quest completion is listed:
 * skill levels, quest points and item requirements are deliberately ignored.
 * Only direct prerequisites are needed; chains resolve themselves because a prerequisite
 * can't be completed without its own prerequisites.
 *
 * Search for "FA-VERIFY" to find entries that need double-checking.
 */
final class QuestRequirements
{
	/**
	 * Never rolled directly. Recipe for Disaster is rolled one subquest at a time instead
	 * (the parent quest completes automatically once every subquest is done).
	 */
	static final Set<Quest> NEVER_ROLLED = ImmutableSet.of(RECIPE_FOR_DISASTER);

	private static final Map<Quest, List<Quest>> PREREQS = new EnumMap<>(Quest.class);

	static
	{
		// --- Quests ---
		req(ANIMAL_MAGNETISM, ERNEST_THE_CHICKEN, PRIEST_IN_PERIL, THE_RESTLESS_GHOST);
		req(ANOTHER_SLICE_OF_HAM, DEATH_TO_THE_DORGESHUUN, THE_GIANT_DWARF, THE_DIG_SITE);
		req(AT_FIRST_LIGHT, CHILDREN_OF_THE_SUN, EAGLES_PEAK);
		req(BENEATH_CURSED_SANDS, CONTACT);
		req(BETWEEN_A_ROCK, DWARF_CANNON, FISHING_CONTEST);
		req(BIOHAZARD, PLAGUE_CITY);
		req(BONE_VOYAGE, THE_DIG_SITE);
		req(CABIN_FEVER, PIRATES_TREASURE, RUM_DEAL, PRIEST_IN_PERIL);
		req(CLIENT_OF_KOUREND, X_MARKS_THE_SPOT);
		req(CONTACT, PRINCE_ALI_RESCUE, ICTHLARINS_LITTLE_HELPER);
		req(CREATURE_OF_FENKENSTRAIN, PRIEST_IN_PERIL, THE_RESTLESS_GHOST);
		req(CURRENT_AFFAIRS, PANDEMONIUM);
		req(DARKNESS_OF_HALLOWVALE, IN_AID_OF_THE_MYREQUE);
		req(DEATH_ON_THE_ISLE, CHILDREN_OF_THE_SUN);
		req(DEATH_TO_THE_DORGESHUUN, THE_LOST_TRIBE);
		req(DEFENDER_OF_VARROCK, SHIELD_OF_ARRAV, TEMPLE_OF_IKOV, BELOW_ICE_MOUNTAIN, FAMILY_CREST,
			GARDEN_OF_TRANQUILLITY, WHAT_LIES_BELOW, ROMEO__JULIET, DEMON_SLAYER);
		req(DESERT_TREASURE_I, THE_DIG_SITE, TEMPLE_OF_IKOV, THE_TOURIST_TRAP, TROLL_STRONGHOLD,
			PRIEST_IN_PERIL, WATERFALL_QUEST);
		req(DESERT_TREASURE_II__THE_FALLEN_EMPIRE, DESERT_TREASURE_I, SECRETS_OF_THE_NORTH, ENAKHRAS_LAMENT,
			TEMPLE_OF_THE_EYE, THE_GARDEN_OF_DEATH, BELOW_ICE_MOUNTAIN, HIS_FAITHFUL_SERVANTS);
		req(DEVIOUS_MINDS, WANTED, TROLL_STRONGHOLD, DORICS_QUEST, ENTER_THE_ABYSS);
		req(DRAGON_SLAYER_II, LEGENDS_QUEST, DREAM_MENTOR, A_TAIL_OF_TWO_CATS, ANIMAL_MAGNETISM,
			GHOSTS_AHOY, BONE_VOYAGE, CLIENT_OF_KOUREND);
		req(DREAM_MENTOR, LUNAR_DIPLOMACY, EADGARS_RUSE);
		req(EADGARS_RUSE, DRUIDIC_RITUAL, TROLL_STRONGHOLD);
		req(ELEMENTAL_WORKSHOP_II, ELEMENTAL_WORKSHOP_I);
		req(ETHICALLY_ACQUIRED_ANTIQUITIES, SHIELD_OF_ARRAV, CHILDREN_OF_THE_SUN);
		req(FAIRYTALE_I__GROWING_PAINS, LOST_CITY, NATURE_SPIRIT);
		req(FAIRYTALE_II__CURE_A_QUEEN, FAIRYTALE_I__GROWING_PAINS);
		req(FALLEN_FROM_GRACE, PANDEMONIUM);
		req(FORGETTABLE_TALE, THE_GIANT_DWARF, FISHING_CONTEST);
		req(GARDEN_OF_TRANQUILLITY, CREATURE_OF_FENKENSTRAIN);
		req(GHOSTS_AHOY, PRIEST_IN_PERIL, THE_RESTLESS_GHOST);
		req(GRIM_TALES, WITCHS_HOUSE);
		req(HAUNTED_MINE, PRIEST_IN_PERIL);
		req(HEROES_QUEST, SHIELD_OF_ARRAV, LOST_CITY, MERLINS_CRYSTAL, DRAGON_SLAYER_I);
		req(HOLY_GRAIL, MERLINS_CRYSTAL);
		req(ICTHLARINS_LITTLE_HELPER, GERTRUDES_CAT);
		req(IN_AID_OF_THE_MYREQUE, IN_SEARCH_OF_THE_MYREQUE);
		req(IN_SEARCH_OF_THE_MYREQUE, NATURE_SPIRIT);
		req(JUNGLE_POTION, DRUIDIC_RITUAL);
		req(KINGS_RANSOM, BLACK_KNIGHTS_FORTRESS, HOLY_GRAIL, MURDER_MYSTERY, ONE_SMALL_FAVOUR);
		req(A_KINGDOM_DIVIDED, THE_DEPTHS_OF_DESPAIR, THE_QUEEN_OF_THIEVES, THE_ASCENT_OF_ARCEUUS,
			THE_FORSAKEN_TOWER, TALE_OF_THE_RIGHTEOUS);
		req(LAND_OF_THE_GOBLINS, ANOTHER_SLICE_OF_HAM, FISHING_CONTEST);
		req(LEGENDS_QUEST, FAMILY_CREST, HEROES_QUEST, SHILO_VILLAGE, UNDERGROUND_PASS, WATERFALL_QUEST);
		req(THE_LOST_TRIBE, GOBLIN_DIPLOMACY, RUNE_MYSTERIES);
		req(LUNAR_DIPLOMACY, THE_FREMENNIK_TRIALS, LOST_CITY, RUNE_MYSTERIES, SHILO_VILLAGE);
		req(MAKING_FRIENDS_WITH_MY_ARM, MY_ARMS_BIG_ADVENTURE, SWAN_SONG, COLD_WAR, ROMEO__JULIET);
		req(MAKING_HISTORY, PRIEST_IN_PERIL, THE_RESTLESS_GHOST);
		req(MONKEY_MADNESS_I, THE_GRAND_TREE, TREE_GNOME_VILLAGE);
		req(MONKEY_MADNESS_II, ENLIGHTENED_JOURNEY, THE_EYES_OF_GLOUPHRIE, RECIPE_FOR_DISASTER__KING_AWOWOGEI,
			TROLL_STRONGHOLD, WATCHTOWER, MONKEY_MADNESS_I);
		req(MOURNINGS_END_PART_I, ROVING_ELVES, BIG_CHOMPY_BIRD_HUNTING, SHEEP_HERDER);
		req(MOURNINGS_END_PART_II, MOURNINGS_END_PART_I);
		req(MY_ARMS_BIG_ADVENTURE, EADGARS_RUSE, THE_FEUD, JUNGLE_POTION);
		req(NATURE_SPIRIT, PRIEST_IN_PERIL, THE_RESTLESS_GHOST);
		req(A_NIGHT_AT_THE_THEATRE, A_TASTE_OF_HOPE);
		req(OLAFS_QUEST, THE_FREMENNIK_TRIALS);
		req(ONE_SMALL_FAVOUR, RUNE_MYSTERIES, SHILO_VILLAGE);
		req(THE_DEPTHS_OF_DESPAIR, CLIENT_OF_KOUREND);
		req(THE_EYES_OF_GLOUPHRIE, THE_GRAND_TREE);
		req(THE_FINAL_DAWN, THE_HEART_OF_DARKNESS, PERILOUS_MOONS);
		req(THE_FORSAKEN_TOWER, CLIENT_OF_KOUREND);
		req(THE_FREMENNIK_EXILES, THE_FREMENNIK_ISLES, LUNAR_DIPLOMACY, MOUNTAIN_DAUGHTER, HEROES_QUEST);
		req(THE_FREMENNIK_ISLES, THE_FREMENNIK_TRIALS);
		req(THE_CURSE_OF_ARRAV, DEFENDER_OF_VARROCK, TROLL_ROMANCE);
		req(THE_GREAT_BRAIN_ROBBERY, CREATURE_OF_FENKENSTRAIN, CABIN_FEVER, RECIPE_FOR_DISASTER__PIRATE_PETE);
		req(THE_HEART_OF_DARKNESS, TWILIGHTS_PROMISE);
		req(THE_PATH_OF_GLOUPHRIE, THE_EYES_OF_GLOUPHRIE, WATERFALL_QUEST, TREE_GNOME_VILLAGE);
		req(THE_QUEEN_OF_THIEVES, CLIENT_OF_KOUREND);
		req(THE_RED_REEF, TROUBLED_TORTUGANS);
		req(THE_SLUG_MENACE, WANTED, SEA_SLUG);
		req(MEAT_AND_GREET, CHILDREN_OF_THE_SUN);
		req(PERILOUS_MOONS, TWILIGHTS_PROMISE);
		req(PRYING_TIMES, PANDEMONIUM, THE_KNIGHTS_SWORD);
		req(RAG_AND_BONE_MAN_II, RAG_AND_BONE_MAN_I, CREATURE_OF_FENKENSTRAIN, ZOGRE_FLESH_EATERS, SKIPPY_AND_THE_MOGRES);
		req(RATCATCHERS, ICTHLARINS_LITTLE_HELPER);
		req(RECRUITMENT_DRIVE, BLACK_KNIGHTS_FORTRESS, DRUIDIC_RITUAL);
		req(REGICIDE, UNDERGROUND_PASS);
		req(ROVING_ELVES, REGICIDE, WATERFALL_QUEST);
		req(ROYAL_TROUBLE, THRONE_OF_MISCELLANIA);
		req(RUM_DEAL, ZOGRE_FLESH_EATERS, PRIEST_IN_PERIL);
		req(SCRAMBLED, CHILDREN_OF_THE_SUN);
		req(SECRETS_OF_THE_NORTH, MAKING_FRIENDS_WITH_MY_ARM, THE_GENERALS_SHADOW, DEVIOUS_MINDS, HAZEEL_CULT);
		req(SHADES_OF_MORTTON, PRIEST_IN_PERIL);
		req(SHADOW_OF_THE_STORM, DEMON_SLAYER, THE_GOLEM);
		req(SHADOWS_OF_CUSTODIA, CHILDREN_OF_THE_SUN);
		req(SHILO_VILLAGE, JUNGLE_POTION);
		req(SINS_OF_THE_FATHER, VAMPYRE_SLAYER, A_TASTE_OF_HOPE);
		req(SONG_OF_THE_ELVES, MOURNINGS_END_PART_II, MAKING_HISTORY);
		req(SWAN_SONG, ONE_SMALL_FAVOUR, GARDEN_OF_TRANQUILLITY);
		req(TAI_BWO_WANNAI_TRIO, JUNGLE_POTION);
		req(A_TAIL_OF_TWO_CATS, ICTHLARINS_LITTLE_HELPER);
		req(TALE_OF_THE_RIGHTEOUS, CLIENT_OF_KOUREND);
		req(A_TASTE_OF_HOPE, DARKNESS_OF_HALLOWVALE);
		req(TEMPLE_OF_THE_EYE, ENTER_THE_ABYSS);
		req(THRONE_OF_MISCELLANIA, HEROES_QUEST, THE_FREMENNIK_TRIALS);
		req(TROLL_ROMANCE, TROLL_STRONGHOLD);
		req(TROLL_STRONGHOLD, DEATH_PLATEAU);
		req(TROUBLED_TORTUGANS, PANDEMONIUM);
		req(TWILIGHTS_PROMISE, CHILDREN_OF_THE_SUN);
		req(UNDERGROUND_PASS, BIOHAZARD);
		req(WANTED, RECRUITMENT_DRIVE, THE_LOST_TRIBE, PRIEST_IN_PERIL, ENTER_THE_ABYSS);
		req(WHAT_LIES_BELOW, RUNE_MYSTERIES);
		req(WHILE_GUTHIX_SLEEPS, DEFENDER_OF_VARROCK, DREAM_MENTOR, THE_HAND_IN_THE_SAND, THE_PATH_OF_GLOUPHRIE, TEARS_OF_GUTHIX, WANTED, FIGHT_ARENA, TEMPLE_OF_THE_EYE, NATURE_SPIRIT, A_TAIL_OF_TWO_CATS);
		req(ZOGRE_FLESH_EATERS, BIG_CHOMPY_BIRD_HUNTING, JUNGLE_POTION);
		req(THE_BLOOD_MOON_RISES, A_NIGHT_AT_THE_THEATRE, SINS_OF_THE_FATHER);
		req(CRAB_QUEST, PANDEMONIUM);
		req(THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE, CHILDREN_OF_THE_SUN);

		// --- Recipe for Disaster subquests ---
		req(RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, COOKS_ASSISTANT);
		req(RECIPE_FOR_DISASTER__MOUNTAIN_DWARF, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, FISHING_CONTEST);
		req(RECIPE_FOR_DISASTER__WARTFACE__BENTNOZE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, GOBLIN_DIPLOMACY);
		req(RECIPE_FOR_DISASTER__PIRATE_PETE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST);
		req(RECIPE_FOR_DISASTER__LUMBRIDGE_GUIDE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, BIG_CHOMPY_BIRD_HUNTING,
			BIOHAZARD, DEMON_SLAYER, MURDER_MYSTERY, NATURE_SPIRIT, WITCHS_HOUSE);
		req(RECIPE_FOR_DISASTER__EVIL_DAVE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, GERTRUDES_CAT, SHADOW_OF_THE_STORM);
		req(RECIPE_FOR_DISASTER__SKRACH_UGLOGWEE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, BIG_CHOMPY_BIRD_HUNTING);
		req(RECIPE_FOR_DISASTER__SIR_AMIK_VARZE, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST,
			LEGENDS_QUEST); // FA-VERIFY: in-game only Legends' Quest *started* is needed
		req(RECIPE_FOR_DISASTER__KING_AWOWOGEI, RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST, MONKEY_MADNESS_I);
		req(RECIPE_FOR_DISASTER__CULINAROMANCER, RECIPE_FOR_DISASTER__MOUNTAIN_DWARF,
			RECIPE_FOR_DISASTER__WARTFACE__BENTNOZE, RECIPE_FOR_DISASTER__PIRATE_PETE,
			RECIPE_FOR_DISASTER__LUMBRIDGE_GUIDE, RECIPE_FOR_DISASTER__EVIL_DAVE,
			RECIPE_FOR_DISASTER__SKRACH_UGLOGWEE, RECIPE_FOR_DISASTER__SIR_AMIK_VARZE,
			RECIPE_FOR_DISASTER__KING_AWOWOGEI, DESERT_TREASURE_I, HORROR_FROM_THE_DEEP);

		// --- Miniquests ---
		req(BARBARIAN_TRAINING, DRUIDIC_RITUAL, TAI_BWO_WANNAI_TRIO);
		req(CURSE_OF_THE_EMPTY_LORD, THE_RESTLESS_GHOST, DESERT_TREASURE_I);
		req(ENTER_THE_ABYSS, RUNE_MYSTERIES);
		req(FAMILY_PEST, THE_GIANT_DWARF);
		req(HIS_FAITHFUL_SERVANTS, PRIEST_IN_PERIL);
		req(HOPESPEARS_WILL, LAND_OF_THE_GOBLINS, THE_RESTLESS_GHOST, DESERT_TREASURE_I, FAIRYTALE_II__CURE_A_QUEEN);
		req(INTO_THE_TOMBS, BENEATH_CURSED_SANDS);
		req(LAIR_OF_TARN_RAZORLOR, HAUNTED_MINE);
		req(MAGE_ARENA_II, MAGE_ARENA_I);
		req(THE_ENCHANTED_KEY, MAKING_HISTORY);
		req(THE_FROZEN_DOOR, DESERT_TREASURE_I);
		req(THE_GENERALS_SHADOW, CURSE_OF_THE_EMPTY_LORD, FIGHT_ARENA);
		// Every other quest/miniquest has no quest requirements.
	}

	private static void req(Quest quest, Quest... prereqs)
	{
		PREREQS.put(quest, Collections.unmodifiableList(Arrays.asList(prereqs)));
	}

	static List<Quest> prerequisites(Quest quest)
	{
		return PREREQS.getOrDefault(quest, Collections.emptyList());
	}

	private QuestRequirements()
	{
	}
}
